version: "3"
services:
  securityc:
    image: ubuntu-openssl:0.0.33
    command: ["/opt/securityc/cert-gen.sh", "-v"]
    environment:
      - SECURITYC_SERVER_COMMON_NAME=localhost
      - SECURITYC_SERVER_CERT_NAME=server.crt
      - SECURITYC_SERVER_KEY_NAME=server.key
      - SECURITYC_SERVER_KEY_OUTPUT_PATH=/certs
      - SECURITYC_SERVER_CERT_OUTPUT_PATH=/certs
    volumes:
      - ./:/app
      - certs:/certs
  server:
    image: node:8
    command: ["bash", "-c", "while true; do sleep 10; done"]
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - certs:/certs
    environment:
      - TLS_KEY_PATH=/certs/server.key
      - TLS_CERT_PATH=/certs/server.crt
    depends_on:
      - securityc
  client:
    image: ubuntu-openssl:0.0.33
    command: ["bash", "-c", "while true; do sleep 10; done"]
    volumes:
      - ./:/app
      - certs:/certs
    depends_on:
      - securityc
volumes:
  certs:
    driver_opts:
      type: tmpfs
      device: tmpfs
