version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "8000:8000"
    env_file:
      - ./bcoin.env
      - ./secrets.env
    environment:
      BCOIN_HOST: bcoin
    volumes:
      ## Shared volume for configs with app service
      - ./configs:/usr/src/app/configs
      ## Mapping to local files- Handy for dev
      ## uncomment for local webpack
      # - ./dist:/usr/src/app/dist
      ## uncomment when developing packages locally
      # - /path/to/my_module:/usr/src/app/node_modules/my_module
      # - ./node_modules/@bpanel:/usr/src/app/node_modules/@bpanel/
      ## uncomment for server dev
      - ./server:/usr/src/app/server
      # - ./scripts:/usr/src/app/scripts
      ## uncomment for webapp dev
      - ./webapp:/usr/src/app/webapp
    ## Only MacOSX users need --watch-poll
    command: server --dev --watch-poll

  bcoin:
    container_name: bcoin
    build:
      context: .
      dockerfile: Dockerfile-bcoin
      args:
        branch: wallet-rewrite
        # rebuild: 1
    restart: unless-stopped
    environment:
      BCOIN_WALLET_HTTP_HOST: 0.0.0.0
    env_file:
      - ./bcoin.env
      - ./secrets.env
    ports:
      ## Comment these if they conflict with something else you're running.
      #-- Mainnet
      - "8333:8333"
      - "8332:8332" # RPC
      - "8334:8334" # Wallet
      #-- Testnet
      - "18333:18333"
      - "18332:18332" # RPC
      - "18334:18334" # Wallet
      #-- Regtest
      - "48444:48444"
      - "48332:48332" # RPC
      - "48334:48334" # Wallet
    volumes:
      - ./configs:/code/configs
      - ./scripts:/code/scripts
      ## Uncomment to make bcoin chain and wallet database persistant
      - ~/.bcoin_bpanel:/code/.bcoin