version: '3'
services:
  server:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # Handy for dev
      - ./dist:/usr/src/app/dist
      - ./bcoin.config.json:/usr/src/app/bcoin.config.json
      - ./node_modules:/usr/src/app/node_modules
      - ./package.json:/usr/src/app/package.json
      - ./server:/usr/src/app/server
    command: npm run start:dev
