version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      BCOIN_NETWORK: regtest
      BCOIN_API_KEY: my-api-key
      BCOIN_INIT_SCRIPT: test-scripts/dummy-10-wallet-crap.js
    ############
    #   BCOIN_NETWORK: testnet
    #   BCOIN_API_KEY: my-other-api-key
    #   BCOIN_INIT_SCRIPT: test-scripts/dummy-10-wallet-crap.js
    ############
    #   BCOIN_NETWORK: mainnet
    #   BCOIN_API_KEY: my-api-key
    #   BCOIN_INIT_SCRIPT: test-scripts/dummy-10-wallet-crap.js
    volumes:
      # mapping to local files- Handy for dev
      - ./dist:/usr/src/app/dist
      - ./bcoin.config.json:/usr/src/app/bcoin.config.json
      - ./node_modules:/usr/src/app/node_modules
      - ./package.json:/usr/src/app/package.json
      - ./server:/usr/src/app/server
      - ./docker-config-init.js:/usr/src/app/docker-config-init.js
    command: ["npm", "run", "start:docker"]
  bcoin:
    container_name: bcoin
    build:
      context: .
      dockerfile: Dockerfile-bcoin
    restart: unless-stopped
    ports:
      # comment these if they conflict with something else youre running.
      #-- Mainnet
      # - "8333:8333"
      # - "8332:8332" # RPC
      #-- Testnet
     # - "18333:18333"
      # - "18332:18332" # RPC
      #-- Regtest
      - "48444:48444"
      - "48332:48332" # RPC
    volumes:
      - ./bcoin.config.json:/usr/src/app/bcoin.config.json
      # Comment one of these out to make them not-persistant
      # - "chain:~/.bcoin/regtest/chain.db"
      # - "wallet:~/.bcoin/regtest/wallet.db"
    depends_on:
      - app

volumes:
  chain:
  wallet: