version: '3'
services:
  server:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # Handy for dev
      - ./dist:/usr/src/app/dist
      - ./server:/usr/src/app/server
