version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "8000:8000"
    env_file: ./secrets.env
    environment:
      ########### Default/Shared configs
      BCOIN_HTTP_HOST: 0.0.0.0
      BCOIN_HOST: bcoin
      BCOIN_LOG_LEVEL: 'debug'
      BCOIN_WORKERS: 'true'
      BCOIN_PREFIX: '/code/.bcoin'
      BCOIN_MEMORY: 'false'
    ############ Regtest
      BCOIN_URI: http://bcoin:48332
      BCOIN_PORT: 48332
      BCOIN_WALLET_PORT: 48334
      BCOIN_INIT_SCRIPT: funded-dummy-wallets.js
      BCOIN_NETWORK: regtest
    ############ Testnet
      # BCOIN_URI: http://bcoin:18332
      # BCOIN_PORT: 18332
      # BCOIN_WALLET_PORT: 18334
      # BCOIN_NETWORK: testnet
      # BCOIN_PRUNE: 'true'
      # BCOIN_DB: 'leveldb'
    ############ Mainnet
      # BCOIN_URI:
      # BCOIN_PORT: 8332
      # BCOIN_WALLET_PORT: 8334
      # BCOIN_NETWORK: mainnet
      # BCOIN_INIT_SCRIPT: test-scripts/dummy-10-wallet.js
    volumes:
      ## Shared volume for configs with app service
      - ./configs:/usr/src/app/configs
      ## Mapping to local files- Handy for dev
      ## uncomment for local webpack
      # - ./dist:/usr/src/app/dist
      ## uncomment when developing packages locally
      # - ./node_modules/my_package:/usr/src/app/node_modules/my_package
      ## uncomment for server dev
      # - ./server:/usr/src/app/server
      ## uncomment for webapp dev
      - ./webapp:/usr/src/app/webapp
    ## Only MacOSX users need --watch-poll
    command: server --dev --watch-poll

  bcoin:
    container_name: bcoin
    build:
      context: .
      dockerfile: Dockerfile-bcoin
      args:
        branch: wallet-rewrite
        # repo:   https://github.com/thann/bcoin.git
        # rebuild: 1
    restart: unless-stopped
    environment:
      BCOIN_WALLET_HTTP_HOST: 0.0.0.0
      BLOCKS_2_MINE: 101
    ports:
      ## Comment these if they conflict with something else you're running.
      #-- Mainnet
      - "8333:8333"
      - "8332:8332" # RPC
      - "8334:8334" # Wallet
      #-- Testnet
      - "18333:18333"
      - "18332:18332" # RPC
      - "18334:18334" # Wallet
      #-- Regtest
      - "48444:48444"
      - "48332:48332" # RPC
      - "48334:48334" # Wallet
    volumes:
      - ./configs:/code/configs
      - ./scripts:/code/scripts
      ## Uncomment to make bcoin chain and wallet database persistant
      # - ~/.bcoin_bpanel:/code/.bcoin
    depends_on:
      - app
