version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "8000:8000"
    env_file: ./secrets.env
    environment:
      BCOIN_HTTP_HOST: 0.0.0.0
      BCOIN_LOG_LEVEL: 'debug'
    ############ Regtest
      BCOIN_URI: http://bcoin:48332
      BCOIN_INIT_SCRIPT: funded-dummy-wallets.js
      BCOIN_NETWORK: regtest
    ############ Testnet
      # BCOIN_URI: http://bcoin:18332
      # BCOIN_NETWORK: testnet
      # BCOIN_PRUNE: 'true'
      # BCOIN_PREFIX: '/code/.bcoin/testnet/'
      # BCOIN_DB: 'leveldb'
    ############ Mainnet
    #   BCOIN_NETWORK: mainnet
    #   BCOIN_INIT_SCRIPT: test-scripts/dummy-10-wallet.js
    volumes:
      # shared volume for configs with app service
      - configs:/usr/src/app/configs
      # mapping to local files- Handy for dev
      - ./dist:/usr/src/app/dist
      - ./node_modules:/usr/src/app/node_modules
      - ./package.json:/usr/src/app/package.json
      - ./server:/usr/src/app/server
      # - ./scripts/docker-config-init.js:/usr/src/app/docker-config-init.js
    command: ["npm", "run", "start:docker"]

  bcoin:
    container_name: bcoin
    build:
      context: .
      dockerfile: Dockerfile-bcoin
    restart: unless-stopped
    ports:
      # comment these if they conflict with something else you're running.
      #-- Mainnet
      - "8333:8333"
      - "8332:8332" # RPC
      #-- Testnet
      - "18333:18333"
      - "18332:18332" # RPC
      #-- Regtest
      - "48444:48444"
      - "48332:48332" # RPC
    volumes:
      - configs:/code/configs
      - ./scripts:/code/scripts
      # Uncomment to make these persistant
      # - "~/.bcoin/testnet/chain.ldb:/code/.bcoin/testnet/chain.ldb"
      # - "~/.bcoin/testnet/walletdb.ldb:/code/.bcoin/testnet/walletdb.ldb"
    depends_on:
      - app
volumes:
  configs:
