version: '3'
services:
  app:
    ## Build to use locak Dockerfile
    # build: .
    ## Use image to to pull from docker
    image: bpanel/bpanel
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "8000:8000"
    env_file:
      - ./secrets.env
    environment:
      BPANEL_HOST: bcoin
      BPANEL_NETWORK: regtest
    volumes:
      ## Mapping to local files- Handy for dev
      - ./webapp:/usr/src/app/webapp
      - ./server:/usr/src/app/server
      # - ./scripts:/usr/src/app/scripts
      # Use below to copy local bpanel config files
      - ~/.bpanel:/root/.bpanel
    ## Only MacOSX users need --watch-poll
    command: server --dev --watch-poll

  securityc:
    image: bpanel/securityc
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./securityc.env
    volumes:
      # mount local cert directory into container
      - certs:/etc/ssl/nginx

  bcoin:
    ## Use image to to pull from docker hub
    image: bpanel/bcoin
    ## Build to use locak Dockerfile-bcoin
    # build:
    #   context: .
    #   dockerfile: Dockerfile-bcoin
    #   # args:
    #   #   repo: https://github.com/bcoin-org/bcoin.git
    #   #   branch: master
    #   #   rebuild: 0
    restart: unless-stopped
    env_file:
    #   - ./bcoin.env
      - ./secrets.env
    environment:
      # can change these based on the node you want to run
      # also can be done via a bcoin.conf file
      BCOIN_NETWORK: regtest
      BCOIN_HTTP_HOST: 0.0.0.0
      # no wallet because default loads bmultisig separately
      BCOIN_NO_WALLET: 'true'
      BCOIN_MEMORY: 'false'
    ports:
      ## Comment these if they conflict with something else you're running.
      #-- Mainnet
      - "8333:8333"
      - "8332:8332" # RPC
      - "8334:8334" # Wallet
      #-- Testnet
      - "18333:18333"
      - "18332:18332" # RPC
      - "18334:18334" # Wallet
      #-- Regtest
      - "48444:48444"
      - "48332:48332" # RPC
      - "48334:48334" # Wallet
      #-- Simnet
      - "18555:18555"
      - "18556:18556" # RPC
      - "18558:18558" # Wallet
    volumes:
      - ./scripts:/code/scripts
      # Use below config to persist bcoin data in docker volume
      # - bcoin:/root/.bcoin
      # Use below config instead to use bcoin data from local home dir
      - ~/.bcoin:/root/.bcoin

volumes:
  certs:
  bcoin:
